### ISSUE TITLE
Problem installing txsocksx

### ISSUE THREAD

**Issue by mvrozanti** [dirtyfilthy/freshonions-torscraper#29]
Upon installing requirements, I get the following error on txsocksx

```
Collecting txsocksx (from -r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/ed/36/5bc796eb2612b500baa26a68481d699e08af5382152a9de18e5a45b44ea7/txsocksx-1.15.0.2.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: zip_safe flag not set; analyzing archive contents...

    Installed /tmp/pip-install-wsr9xyns/txsocksx/.eggs/vcversioner-2.16.0.0-py3.7.egg
    error in txsocksx setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; 'int' object is not iterable
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-wsr9xyns/txsocksx/
```

I think [this is probably the same issue](https://github.com/habnabit/txsocksx/issues/16) but this means this repo does not support python 3.x+ as a consequence. Has anyone managed to fix this and getting it to run on python 3?

What exactly does this dependency do? Can it be replaced? I'm amazed at the number of dependencies in this project.

**Comment by L3houx** [comment]
Hi @mvrozanti, the project run on Python 2. The dependency "txsocksx" is used to connect the crawler over tor. The project contained a lot of dependencies (like you said) and it's pretty hard to change 1 version or 1 dependency because it has a lot of dependencies between them. Also, the project isn't updated by the maintainer. GoSecure fork the project and add a lot of nice functionalities, so you should look at our fork https://github.com/GoSecure/freshonions-torscraper. I finished dockerizing the project 2-3 days ago.
